version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "course"
      POSTGRES_USER: "course"
      POSTGRES_PASSWORD: "course"
    ports:
      - "5432:5432"
